[package]
name = "wow_world_messages"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.wow_world_base]
path = "../wow_world_base"
features = ["vanilla", "tbc", "wrath"]

[dependencies.wow_srp]
version = "0.5.1"
default-features = false
optional = true
features = ["wrath-header", "tbc-header"]

[features]
default = ["encryption"]
sync = []
vanilla = []
tbc = []
wrath = []
encryption = ["wow_srp"]

[dependencies.tokio]
version = "1"
default-features = false
features = ["io-util"]
optional = true

[dependencies.async-std]
version = "1.11"
default-features = false
optional = true
features = ["async-io"]

[dev-dependencies.async-std]
version = "1.11"
default-features = false
features = ["attributes", "default"]

[dev-dependencies.tokio]
version = "1"
default-features = false
features = ["macros", "rt"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
