name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - wow_login_messages-v[0-9]+.*
      - wow_world_messages-v[0-9]+.*
      - wow_world_base-v[0-9]+.*
      - wow_items-v[0-9]+.*
      - wow_spells-v[0-9]+.*

jobs:
  login-messages:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/wow_login_messages-v')
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: wow_login_messages/CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  world-messages:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/wow_world_messages-v')
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: wow_world_messages/CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  world-base:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/wow_world_base-v')
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: wow_world_base/CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  items:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/wow_items-v')
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: wow_items/CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  spells:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/wow_spells-v')
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: wow_spells/CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
