pre-release-replacements = [
  {file="README.md", search="version = \"[a-z0-9\\+.-]+\"", replace="version = \"{{version}}\"", exactly=1},

  {file="src/lib.rs", search="version = \"[a-z0-9\\+.-]+\"", replace="version = \"{{version}}\"", exactly=1},

  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}", min=1},
  {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}", exactly=1},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}", min=1},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n## [Unreleased] - ReleaseDate\n", exactly=1},
  {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://github.com/gtker/wow_messages/compare/{{tag_name}}...HEAD", exactly=1},
]
